### ISSUE TITLE
Chests in recipe

### ISSUE THREAD

**Issue by HyperRaccoon13** [Erdragh/ProjectTable#4]
its 1:48 a.m so sorry if no make sense
first create this path: `resources/data/c/tags/items/wooden_chests.json`
in this json, add the following code:
``` 
{
  "replace": false,
  "values": [
    "minecraft:chest",
    "minecraft:trapped_chest",
    "ad_astra:strophar_chest",
    "ad_astra:aeronos_chest"
  ]
}
```

Once done
Create this path: `resources/data/projecttabble/recipes/projecttable.json`
in this file, add the following code:
```
{
  "type": "minecraft:crafting_shaped",
  "pattern": [
    "SSS",
    "PTP",
    "PCP"
  ],
  "key": {
    "S": {
      "item": "minecraft:stone"
    },
    "P": {
      "tag": "minecraft:planks"
    },
    "T": {
      "item": "minecraft:crafting_table"
    },
    "C": {
      "tag": "c:wooden_chests"
    }
  },
  "result": {
    "item": "projecttable:projecttable",
    "count": 1
  }
}
```
Let me know if you run into problems
but when you load the game with this files, you should see this: 
![image](https://github.com/Erdragh/ProjectTable/assets/68512889/d65db895-69b2-47ca-8021-35dd7da911bf)

**Comment by Erdragh** [comment]
Ok, so:

wooden_chests is probably not a widely used common tag. The fabric wiki specifies c:chest and c:workbench for chests and crafting tables respectively.

But thanks to this issue I noticed the mistake I made, I had items/tags instead of tags/items.

I will close this issue and the PR associated. Thanks!
